# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'DigitsFYF' do
  pod 'Fabric', '~> 1.5.1' 
  pod 'TwitterCore', '~> 1.9.0'
  pod 'Digits', '~> 1.9.0'
  pod 'AWSCognito', '~> 2.2.6'
  pod 'AWSDynamoDB', '~> 2.2.6'
end
